data:
  # specify the relative path of your data files
  path: "./data"

responsibility:
  # create a dictionary for each contributor in your project, featuring
  # their first name (forename), last name (surname), and ORCID (ptr)
  resp: [{"forename":"Kelly", 
          "surname":"Christensen", 
          "ptr":{"type":"orcid","target":"000000027236874X"}},

        {"forename":"Simon",
        "surname":"Gabay", 
        "ptr":{"type":"orcid","target":"0000000190944475"}}]

  # name the publisher of this digital edition (project name)
  publisher: "Gallic(orpor)a"
  # name which authority finances or supports the project
  authority: "BnF DATALab"
  # specify the edition's availability to the public/licencing
  availability: {"status": "restricted", "n":"cc-by"}
  licence: {"target":"https://creativecommons.org/licenses/by/4.0/"}
