name: "Transform"
on:
  push:
    paths:
      - "./data/**"
jobs:
  Transform:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install requests
      - name: "Create TEI files"
        run: |
          python transform/alto2tei.py ./data/*
      - name: "Commit generated files to ./data/"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./data/*.xml
          git commit -m "Create TEI files" || echo "Nothing to commit"
          git push || echo "Nothing to push"
